### ISSUE TITLE
License for Application is Not Correct

### ISSUE THREAD

**Issue by cameronbosch** [flathub/org.mintguide.WebAppReader#3]
As far as I know, [on the author of the application's website](https://mintguide.org/post/webappreader/), the author says something that concerns me regarding the license (point 3):

"The distribution of modified versions of the software without prior written permission from the author is prohibited."

The first two points perfectly are allowed under the MIT license, but (I'm not a legal expert) I believe that this final point makes this app incompatible with the stated license, the MIT license, or any FOSS license. Could somebody please fix the Flathub License label for this app change it to "proprietary" unless the application's author decides to drop this condition?

**Comment by ShvonderSiN** [comment]
looks like you are right,,, i will fix it

**Comment by ShvonderSiN** [comment]
fixed, thx
